// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using mission6.Models;

namespace mission6.Migrations
{
    [DbContext(typeof(TaskContext))]
    [Migration("20220209010018_MyFirstMigration")]
    partial class MyFirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22");

            modelBuilder.Entity("mission6.Models.Category", b =>
                {
                    b.Property<int>("Categoryid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryName")
                        .HasColumnType("TEXT");

                    b.HasKey("Categoryid");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Categoryid = 1,
                            CategoryName = "Home"
                        },
                        new
                        {
                            Categoryid = 2,
                            CategoryName = "School"
                        },
                        new
                        {
                            Categoryid = 3,
                            CategoryName = "Work"
                        },
                        new
                        {
                            Categoryid = 4,
                            CategoryName = "Church"
                        });
                });

            modelBuilder.Entity("mission6.Models.Task", b =>
                {
                    b.Property<int>("TaskID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Categoryid")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Completed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quadrant")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TaskName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TaskID");

                    b.HasIndex("Categoryid");

                    b.ToTable("Tasks");

                    b.HasData(
                        new
                        {
                            TaskID = 1,
                            Categoryid = 2,
                            Completed = false,
                            DueDate = "2/9",
                            Quadrant = 1,
                            TaskName = "Mission 6 Project"
                        },
                        new
                        {
                            TaskID = 2,
                            Categoryid = 2,
                            Completed = false,
                            DueDate = "2/10",
                            Quadrant = 2,
                            TaskName = "Authorization Lab"
                        });
                });

            modelBuilder.Entity("mission6.Models.Task", b =>
                {
                    b.HasOne("mission6.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("Categoryid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
